name = "LaminarFamiliesMaximalBinaryTrees"
version = "0.1.0"
defaultTargets = ["LaminarFamiliesMaximalBinaryTrees"]

releaseRepo = "https://github.com/SmaniaD/LaminarFamiliesMaximalBinaryTrees"
preferReleaseBuild = true

[[lean_lib]]
name = "LaminarFamiliesMaximalBinaryTrees"

[[require]]
name  = "mathlib"
scope = "leanprover-community"
 

