name = "LaminarFamiliesMaximalBinaryTrees"
version = "0.1.0"
defaultTargets = ["LaminarFamiliesMaximalBinaryTrees"]

[[lean_lib]]
name = "LaminarFamiliesMaximalBinaryTrees"

[[require]]
name  = "mathlib"
scope = "leanprover-community"
 

